version: 2
jobs:
  build:
    docker:
      - image: quramy/opencvjs-emcc:sdk-tag-1.37.21-64bit

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: get src
          command: |
            git clone opencv/opencv
            git checkout 3.1.0
      - run:
          name: build wasm
          command: |
            python make.py --wasm

      - store_artifacts:
          path: build
          destination: wasm
